apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-app
  labels:
    app: log-output-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: shared-data-claim
      containers:
        - name: log-writer
          image: log-output:latest
          imagePullPolicy: Never
          command: ["/log-output", "writer"]
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
        - name: log-reader
          image: log-output:latest
          imagePullPolicy: Never
          command: ["/log-output", "reader"]
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
