apiVersion: v1
kind: Service
metadata:
  name: log-output-service
  namespace: exercises
  labels:
    app: log-output-app
spec:
  selector:
    app: log-output-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
