apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app
  labels:
    app: pingpong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data-claim
      containers:
        - name: pingpong
          image: pingpong:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/files
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
