apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app
  namespace: exercises
  labels:
    app: pingpong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      containers:
        - name: pingpong
          image: pingpong:latest
          imagePullPolicy: Never
          env:
            - name: POSTGRES_HOST
              value: "postgres-stset-0.postgres-svc.exercises.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "pingponguser"
            - name: POSTGRES_PASSWORD
              value: "pingpongpass"
            - name: POSTGRES_DB
              value: "pingpongdb"
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
