apiVersion: v1
kind: Service
metadata:
  name: pingpong-service
  namespace: exercises
  labels:
    app: pingpong-app
spec:
  selector:
    app: pingpong-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

