apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-app-images-pv
  labels:
    app: todo-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/todo-app-images
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-images-pvc
  namespace: project
  labels:
    app: todo-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
