apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
  labels:
    app: todo-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: PROJECT/TODO-APP
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: FRONTEND_PORT
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: IMAGE_URL
            - name: CACHE_DURATION_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: CACHE_DURATION_MINUTES
            - name: TODO_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: TODO_BACKEND_URL
            - name: IMAGE_DIRECTORY
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: IMAGE_DIRECTORY
            - name: IMAGE_FILENAME
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: IMAGE_FILENAME
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: LOG_LEVEL
          volumeMounts:
            - name: image-cache
              mountPath: /usr/src/app/images
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: todo-app-images-pvc
