apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: project
type: Opaque
data:
  # Base64 encoded values:
  # POSTGRES_DB: tododb (dG9kb2Ri)
  # POSTGRES_USER: todouser (dG9kb3VzZXI=)
  # POSTGRES_PASSWORD: todopass123 (dG9kb3Bhc3MxMjM=)
  POSTGRES_DB: dG9kb2Ri
  POSTGRES_USER: dG9kb3VzZXI=
  POSTGRES_PASSWORD: dG9kb3Bhc3MxMjM= 