apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-claim
  namespace: exercises
spec:
  storageClassName: shared-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

